### PR TITLE
Fixed to be compatible for 2.8.1

### PR DESCRIPTION
**Pull request by guncebektas**
Hi @todda00 

Meteor.js is moving forward and this package will be deprecated as some breaking changes are coming to Meteor's core. I made some progress in it. 

Can you please review my changes? If you are not interested, I want to publish it under my own repositories. I will also try to put it into community-packages.

### CODE REVIEW

**Comment by todda00** [comment]
Hello @guncebektas . I do not use this package anymore, or Meteor at all. I would be willing to transfer this repository to you for maintenance if you are willing and wish to take that on. 

Let me know and I can transfer it.

**Comment by guncebektas** [comment]
I'm ready to maintain 👍🏼 you can transfer it to me 🙏

**Comment by todda00** [comment]
Ran into issue transferring, I think you may need to rename your existing repo prior to the transfer. See error during transfer:

Transfer_repository

**Comment by guncebektas** [comment]
can you pls try again?

**Comment by todda00** [comment]
Now I am getting: `guncebektas already has a repository in the todda00/meteor-friendly-slugs network` 

I think this is because there is a fork present. 
`The target account must not have a repository with the same name, or a fork in the same network.`
See: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by guncebektas** [comment]
I have completely deleted the fork

**Pull request closed without merging**
